#!/usr/bin/env bash
# configures nginx

sudo apt-get update -y
sudo apt-get install -y nginx
sudo rm /etc/nginx/sites-enabled/default
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By \$hostname;
    }
}" | sudo tee /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
