#!/usr/bin/env bash
# set's up ufw

sudo apt-get update
sudo apt-get upgrade

sudo apt-install ufw -y

sudo ufw default deny incoming
sudo ufw default allow outgoing

sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

yes | sudo ufw enable
