#!/usr/bin/env bash
# nginx user

pkill nginx

sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf

sed -i 's/listen .*/listen 8080;/' /etc/nginx/sites-available/default

sudo -u nginx service nginx start
